# frozen_string_literal: true

require_relative "test_helper"
require "tempfile"
require "truffle/model_catalog_refresh"

class ModelCatalogRefreshTest < Minitest::Test
  FIXTURE = File.expand_path("fixtures/models_dev_api.json", __dir__)

  def test_models_from_selects_supported_chat_models
    models = Truffle::ModelCatalogRefresh.models_from(fixture_data)

    assert_equal %w[claude-fixture-1 gpt-fixture gemini-fixture-1], models.map(&:id)
  end

  def test_models_from_fills_required_cost_keys
    openai = model("gpt-fixture")
    google = model("gemini-fixture-1")
    anthropic = model("claude-fixture-1")

    assert_equal({ input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
                 openai.cost)
    assert_equal({ input: 0.3, output: 2.5, cache_read: 0.03, cache_write: 0.0 },
                 google.cost)
    assert_equal({ input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
                 anthropic.cost)
  end

  def test_models_from_clips_modalities_to_what_truffle_can_send
    assert_equal %i[text image], model("claude-fixture-1").input
    assert_equal %i[text image], model("gemini-fixture-1").input
  end

  def test_models_from_skips_snapshots_when_base_model_is_present
    ids = Truffle::ModelCatalogRefresh.models_from(fixture_data).map(&:id)

    refute_includes ids, "claude-fixture-1-20260101"
  end

  def test_generate_renders_a_ruby_catalog
    catalog = Truffle::ModelCatalogRefresh.generate(fixture_data)

    assert_equal 3, catalog.models.length
    assert_includes catalog.content, "This file is generated by script/refresh-models"
    assert_includes catalog.content, "Model.new(id: \"gpt-fixture\""
    assert_includes catalog.content, "cache_write: 0.0"
    assert_includes catalog.content, "def resolve(reference, models: ALL)"
    assert RubyVM::InstructionSequence.compile(catalog.content)
  end

  def test_load_wraps_bad_json_with_source_context
    error = Tempfile.create("bad-models-json") do |file|
      file.write("{")
      file.close

      assert_raises(Truffle::ModelCatalogRefresh::SourceError) do
        Truffle::ModelCatalogRefresh.load(file.path)
      end
    end

    assert_includes error.message, "failed to parse"
  end

  private

  def fixture_data
    @fixture_data ||= Truffle::ModelCatalogRefresh.load(FIXTURE)
  end

  def model(id)
    Truffle::ModelCatalogRefresh.models_from(fixture_data).find { |candidate| candidate.id == id }
  end
end
