# frozen_string_literal: true

require "json"
require "net/http"
require "uri"

module Truffle
  # Maintenance-only generator for lib/truffle/models.rb.
  #
  # Runtime code must keep using the committed catalog. This module is loaded by
  # script/refresh-models and tests only, so model lookup never fetches the
  # network at require time.
  module ModelCatalogRefresh
    class SourceError < StandardError; end

    SOURCE_URL = "https://models.dev/api.json"
    SUPPORTED_INPUT_MODALITIES = %w[text image].freeze
    SKIP_ID_PATTERN = /embedding|moderation|whisper|transcribe|tts/i

    ProviderSource = Struct.new(:key, :constant, :provider, :api, keyword_init: true)
    ModelSpec = Struct.new(:id, :name, :provider, :api, :context_window,
                           :max_output, :input, :reasoning, :cost, keyword_init: true)
    Catalog = Struct.new(:models, :content, keyword_init: true)

    PROVIDERS = [
      ProviderSource.new(key: "anthropic", constant: "ANTHROPIC",
                         provider: :anthropic, api: :anthropic_messages),
      ProviderSource.new(key: "openai", constant: "OPENAI",
                         provider: :openai, api: :openai_completions),
      ProviderSource.new(key: "google", constant: "GOOGLE",
                         provider: :google, api: :google_generative_ai)
    ].freeze

    module_function

    def fetch(url = SOURCE_URL)
      uri = URI(url)
      response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
        request = Net::HTTP::Get.new(uri)
        request["Accept"] = "application/json"
        http.request(request)
      end

      unless response.is_a?(Net::HTTPSuccess)
        raise SourceError, "failed to fetch #{url}: HTTP #{response.code}"
      end

      JSON.parse(response.body)
    rescue JSON::ParserError => e
      raise SourceError, "failed to parse #{url}: #{e.message}"
    end

    def load(path)
      JSON.parse(File.read(path))
    rescue Errno::ENOENT => e
      raise SourceError, "failed to read #{path}: #{e.message}"
    rescue JSON::ParserError => e
      raise SourceError, "failed to parse #{path}: #{e.message}"
    end

    def generate(data)
      models = models_from(data)

      Catalog.new(models: models, content: render(models))
    end

    def models_from(data)
      PROVIDERS.flat_map do |provider|
        source_models = data.fetch(provider.key, {}).fetch("models", {})
        ids = source_models.keys

        source_models.filter_map do |id, model|
          next unless supported_model?(id, model)
          next if shadowed_snapshot?(id, ids)

          build_model(provider, id, model)
        end.sort_by(&:id)
      end
    end

    def supported_model?(id, model)
      return false if id.match?(SKIP_ID_PATTERN)
      return false if model["open_weights"]

      modalities = model.fetch("modalities", {})
      return false unless Array(modalities["input"]).include?("text")
      return false unless Array(modalities["output"]) == ["text"]

      limit = model["limit"]
      cost = model["cost"]
      limit.is_a?(Hash) && cost.is_a?(Hash) &&
        positive_integer?(limit["context"]) &&
        positive_integer?(limit["output"]) &&
        cost.key?("input") && cost.key?("output")
    end

    def build_model(provider, id, model)
      ModelSpec.new(
        id: id,
        name: model.fetch("name", id),
        provider: provider.provider,
        api: provider.api,
        context_window: integer(model.dig("limit", "context")),
        max_output: integer(model.dig("limit", "output")),
        input: input_modalities(model),
        reasoning: model["reasoning"] == true,
        cost: cost_hash(model.fetch("cost"))
      )
    end

    def render(models)
      provider_blocks = PROVIDERS.map { |provider| render_provider(provider, models) }.join("\n\n")

      <<~RUBY
        # frozen_string_literal: true

        require_relative "model"

        module Truffle
          # The model catalog: every model Truffle knows how to address and price.
          #
          # This file is generated by script/refresh-models from #{SOURCE_URL}.
          # Do not edit model entries by hand; update the generator or source data.
          module Models
        #{provider_blocks}

            ALL = (ANTHROPIC + OPENAI + GOOGLE).freeze

            BY_ID = ALL.to_h { |m| [m.id, m] }.freeze

            module_function

            def all = ALL

            def for_provider(provider)
              ALL.select { |m| m.provider == provider.to_sym }
            end

            def find(id)
              return nil if id.nil?

              BY_ID[id] || BY_ID[base_id(id)]
            end
            class << self
              alias [] find
            end

            def resolve(reference, models: ALL)
              trimmed = reference.to_s.strip
              return nil if trimmed.empty?

              one_of(models) { |m| "\#{m.provider}/\#{m.id}".casecmp?(trimmed) } ||
                resolve_with_provider(trimmed, models) ||
                one_of(models) { |m| id_match?(m, trimmed) }
            end

            def provider_for(reference)
              resolve(reference)&.provider
            end

            def one_of(models, &)
              matches = models.select(&)
              matches.length == 1 ? matches.first : nil
            end

            def resolve_with_provider(reference, models)
              slash = reference.index("/")
              return nil unless slash

              provider = reference[0...slash].strip
              model_id = reference[(slash + 1)..].strip
              return nil if provider.empty? || model_id.empty?

              one_of(models) { |m| m.provider.to_s.casecmp?(provider) && id_match?(m, model_id) }
            end

            def base_id(id)
              id.sub(/-\\d{4}-\\d{2}-\\d{2}\\z/, "").sub(/-\\d{8}\\z/, "")
            end

            def id_match?(model, reference)
              ref = reference.downcase
              id = model.id.downcase
              id == ref || id == base_id(ref)
            end
          end
        end
      RUBY
    end

    def render_provider(provider, models)
      entries = models.select { |model| model.provider == provider.provider }

      <<~RUBY.chomp
            #{provider.constant} = [
        #{entries.map { |model| render_model(model) }.join(",\n")}
            ].freeze
      RUBY
    end

    def render_model(model)
      [
        "      Model.new(id: #{ruby_string(model.id)}, name: #{ruby_string(model.name)},",
        "                provider: :#{model.provider}, api: :#{model.api},",
        "                input: #{symbol_array(model.input)}, reasoning: #{model.reasoning},",
        "                context_window: #{integer_literal(model.context_window)},",
        "                max_output: #{integer_literal(model.max_output)},",
        "                cost: { input: #{float_literal(model.cost.fetch(:input))},",
        "                        output: #{float_literal(model.cost.fetch(:output))},",
        "                        cache_read: #{float_literal(model.cost.fetch(:cache_read))},",
        "                        cache_write: #{float_literal(model.cost.fetch(:cache_write))} })"
      ].join("\n")
    end

    def shadowed_snapshot?(id, ids)
      base = base_id(id)

      base != id && ids.include?(base)
    end

    def input_modalities(model)
      Array(model.dig("modalities", "input")).select do |modality|
        SUPPORTED_INPUT_MODALITIES.include?(modality)
      end.map(&:to_sym)
    end

    def cost_hash(cost)
      { input: float(cost.fetch("input")),
        output: float(cost.fetch("output")),
        cache_read: float(cost.fetch("cache_read", 0)),
        cache_write: float(cost.fetch("cache_write", 0)) }
    end

    def base_id(id)
      id.sub(/-\d{4}-\d{2}-\d{2}\z/, "").sub(/-\d{8}\z/, "")
    end

    def positive_integer?(value)
      integer(value).positive?
    rescue SourceError
      false
    end

    def integer(value)
      Integer(value)
    rescue ArgumentError, TypeError
      raise SourceError, "expected integer value, got #{value.inspect}"
    end

    def float(value)
      Float(value)
    rescue ArgumentError, TypeError
      raise SourceError, "expected numeric value, got #{value.inspect}"
    end

    def ruby_string(value)
      value.to_s.dump
    end

    def symbol_array(values)
      "%i[#{values.join(" ")}]"
    end

    def integer_literal(value)
      value.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1_').reverse
    end

    def float_literal(value)
      float(value).to_s
    end
  end
end
